version: 0.1

environment_variables:
    plaintext:
        S3_BUCKET: "corsearch.com"
        BUILD_ENV: "prod"

phases:
  install:
    commands:
      - printenv
      - npm install      
  build:
    commands:
      - npm run generate
  post_build:
         commands:
            - aws s3 cp dist s3://${S3_BUCKET} --recursive
            - echo Build completed on `date`
   
artifacts:
  #files:
  #  - dist*/**
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes